services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: account_onboarding
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - account-onboarding-data:/var/lib/postgresql/data

volumes:
  account-onboarding-data: