@AccountOnboarding.Api_HostAddress = http://localhost:5227

POST {{AccountOnboarding.Api_HostAddress}}/api/v1/accounts
Content-Type: application/json

{
  "holderName": "Ana Silva",
  "cpf": "529.982.247-25",
  "status": "Active"
}

###